shimataro/value-schema

src/libs/EmailAdjuster.es
Fixed return value on error in EmailAdjuster
=> F: fix on email error

src/libs/StringAdjuster.es
* Delete custom function for StringAdjuster
=> D: delete StringAdjuster.prototype.custom()

src/libs/EmailAdjuster.es, test/libs/EmailAdjuster.test.es
* Support IPv4 for EmailAdjuster
=> U: support IPv4 domain part for EmailAdjuster

npm-shrinkwrap.json, package.json, src/libs/AdjusterError.es, test/index.test.es, test/libs/EmailAdjuster.test.es, test/libs/NumberAdjuster.test.es, test/libs/StringAdjuster.test.es
* change test framework; mocha -> jest
=> U: change test framework; mocha -> jest

src/libs/EmailAdjuster.es, test/libs/EmailAdjuster.test.es
* add `EmailAdjuster.prototype.pattern()`
=> A: add pattern() method to email()

README.md, npm-shrinkwrap.json, package.json
release version 0.1.0
* first release!
=> version 0.1.0

src/index.es, src/libs/adjustData.es
* move `adjustData()` to isolated file
=> R: move adjustData() to isolated file

README.md
* fix ambiguous expression in `README.md`
=> F: fix ambiguous expression

npm-shrinkwrap.json
* Fix the error: `npm test` doesn't work on npm@5
=> F: fix the test error on npm@5

README.md, src/libs/EmailAdjuster.es, src/libs/NumberAdjuster.es, src/libs/StringAdjuster.es, test/libs/EmailAdjuster.test.es, test/libs/NumberAdjuster.test.es, test/libs/StringAdjuster.test.es
* support the value when input is empty string
=> U: enable to specify value to allowEmpty()

src/libs/EmailAdjuster.es
* regular expression for email
=> R: Refactor regular expression for email

test/libs/EmailAdjuster.test.es
* add test for quoted-string email
=> R: add test for quoted-string email

src/libs/EmailAdjuster.es
* import error in `EmailAdjuster.es`
=> F: fix import error in EmailAdjuster.es

src/libs/EmailAdjuster.es, src/libs/IPv4Adjuster.es, src/libs/IPv6Adjuster.es, src/libs/StringAdjuster.es
* change constant name of regular expression
=> R: change constant name of regular expression

README.md, test/index.test.es, test/libs/IPv4Adjuster.test.es
* add example for IPv4/IPv6 in README
=> U: add example for IPv4/IPv6

test/libs/IPv6Adjuster.test.es
* fix test describe and function names for IPv6Adjuster
=> F: fix test describe and function for IPv6Adjuster

README.md
* add example for multiple adjustment in README
=> U: update example for multiple adjustment in README

README.md
* add release note for next version
=> U: update release note in README

README.md
=> F: fix examples in README

.gitignore
* ignore workspace file for [Visual Studio Code](https://code.visualstudio.com/)
=> U: ignore workspace file for Visual Studio Code

README.md
=> F: fix example code in README

src/libs/StringAdjuster.es
=> R: refactor check string

test/libs/NumberAdjuster.test.es
=> F: fix missing semicolons

src/libs/NumberArrayAdjuster.es
* fix import errors in NumberArrayAdjuster
* update JSDoc comments
=> F: fix import errors in NumberArrayAdjuster

src/libs/NumberAdjuster.es
* refactor `adjuster.number()`
=> R: refactor `adjuster.number()`

src/libs/StringAdjuster.es
=> Refactor StringAdjuster

src/libs/NumberAdjuster.es
* move `__adjustType()` to front
* add blank line
=> R: Refactor NumberAdjuster

src/libs/NumberAdjuster.es
* `./AdjusterError.es` -> `./AdjusterError`
=> Fix import error in `NumberAdjuster.es`

src/libs/NumberAdjuster.es, src/libs/StringAdjuster.es
=> U: check type of number/string

src/libs/NumberArrayAdjuster.es
* put AdjusterInterface and AdjusterError side-by-side
=> * put AdjusterInterface and AdjusterError side-by-side

src/libs/AdjusterError.es
* embed original value in AdjusterError
=> U: embed original value in AdjusterError

test/libs/NumberArrayAdjuster.test.es
* fix describe: `(adjusted` => `(adjusted)`
=> F: fix describe: "(adjusted" => "(adjusted)"

.gitignore
* ignore Visual Studio Code setting directory
=> U: ignore Visual Studio Code setting directory

.eslintrc.yml, npm-shrinkwrap.json, package.json, src/libs/AdjusterInterface.es, test/libs/EmailAdjuster.test.es, test/libs/IPv4Adjuster.test.es, test/libs/IPv6Adjuster.test.es, test/libs/NumberAdjuster.test.es, test/libs/NumberArrayAdjuster.test.es, test/libs/StringAdjuster.test.es
=> R: introduce ESLint

.editorconfig
* update reference in `.editorconfig`
=> U: update reference in .editorconfig

.editorconfig, .gitignore, node-adjuster.code-workspace
* add [Visual Studio Code](https://code.visualstudio.com/) workspace file
=> * add Visual Studio Code workspace

README.md
* update basic usage in README
=> U: update basic usage in README

src/libs/StringArrayAdjuster.es
=> F: blank line

.babelrc, .editorconfig
=> U: treat .babelrc as JSON

package.json
* change test directory to "dist"
=> U: change test directory to "dist"

node-adjuster.code-workspace
* update workspace settings for JavaScript
=> U: update workspace settings for JavaScript

.travis.yml
=> U: test macOS

README.md
=> U: add badges in README

package.json
=> Fix dependencies version

README.md, src/index.es, src/libs/NumericStringAdjuster.es, src/libs/constants.es, src/libs/decorators/numericString/checksum.es, src/libs/decorators/numericString/pattern.es, src/libs/decorators/numericString/separatedBy.es, test/index.test.es, test/libs/NumericStringAdjuster.test.es
=> Add numericstring

src/adjusters/email.es, src/adjusters/ipv4.es, src/adjusters/ipv6.es, src/adjusters/number.es, src/adjusters/numberArray.es, src/adjusters/numericString.es, src/adjusters/string.es, src/adjusters/stringArray.es, src/index.es, src/libs/decorators/numberArray/each.es, src/libs/decorators/stringArray/each.es, test/adjusters/email.test.es, test/adjusters/ipv4.test.es, test/adjusters/ipv6.test.es, test/adjusters/number.test.es, test/adjusters/numberArray.test.es, test/adjusters/numericString.test.es, test/adjusters/string.test.es, test/adjusters/stringArray.test.es
* use factory pattern for adjusters
=> R: use factory pattern for adjusters

README.md, src/index.es, src/libs/constants.es, src/libs/decorators/numericString/checksum.es, test/adjusters/numericString.test.es, test/index.test.es
* rename `NUMERIC_STRING_CHECKSUM` to `NUMERIC_STRING_CHECKSUM_ALGORITHM`
=> R: rename NUMERIC_STRING_CHECKSUM to NUMERIC_STRING_CHECKSUM_ALGORITHM

README.md, src/libs/constants.es, src/libs/decorators/numericString/checksum.es, test/adjusters/numericString.test.es
* add ISBN13 algorithm to `adjuster.numericString()`
=> A: ISBN13 algorithm to adjuster.numericString()

test/adjusters/numericString.test.es
* update test for `adjuster.numericString()`
=> U: test for `adjuster.numericString()`

src/libs/AdjusterBase.es
* change `_decorators` to static property
=> R: change `_decorators` to static property

test/adjusters/email.test.es, test/adjusters/ipv4.test.es, test/adjusters/ipv6.test.es, test/adjusters/number.test.es, test/adjusters/numberArray.test.es, test/adjusters/numericString.test.es, test/adjusters/string.test.es, test/adjusters/stringArray.test.es
* change imported modules for test
=> R: change imported modules for test

.babelrc, README.md, package.json, src/index.d.ts
* support complement of [IntelliJ IDEA](https://www.jetbrains.com/idea/)
=> R: support complement of IntelliJ IDEA

README.md, src/adjusters/numericString.es, src/libs/decorators/numericString/joinArray.es, test/adjusters/numericString.test.es
* `adjuster.numericString().joinArray()`
=> A: add `adjuster.numericString().joinArray()`

CHANGELOG.md, README.md
=> * use changelog

src/libs/AdjusterBase.es
* put decorators map into closure function
=> * put decorators map into closure function

src/libs/AdjusterBase.es
=> * refactor params map

.babelrc
* add `"useBuiltIns": true` to babel-preset-env options
=> * add `"useBuiltIns": true` to babel-preset-env options

CHANGELOG.md, README.md, src/adjusters/string.es, src/libs/decorators/string/trim.es, test/adjusters/string.test.es
=> A: add `adjuster.string().trim()`

CHANGELOG.md, README.md, src/adjusters/email.es, test/adjusters/email.test.es
=> A: add `adjuster.email().trim()`

CHANGELOG.md, README.md, src/adjusters/stringArray.es, src/libs/decorators/stringArray/each.es, test/adjusters/stringArray.test.es
* `adjuster.stringArray().eachTrim()`
=> A: add `adjuster.stringArray().eachTrim()`

CHANGELOG.md, README.md, src/adjusters/ipv4.es, test/adjusters/ipv4.test.es
=> A: add `adjuster.ipv4().trim()`

CHANGELOG.md, README.md, src/adjusters/ipv6.es, test/adjusters/ipv6.test.es
=> A: add `adjuster.ipv6().trim()`

README.md, src/libs/adjust.es, test/index.test.es
* rename parameters: `adjusters` -> `constraints`
=> * adjusters -> constraints

src/adjusters/numberArray.es, src/adjusters/numericString.es, src/adjusters/string.es
Fixed
* parameter names for JSDoc
=> F: fix parameter names for JSDoc

src/adjusters/ipv4.es, src/adjusters/ipv6.es
=> F: fix JSDoc for ipv4 / ipv6

CHANGELOG.md, README.md
=> Feature readme

CHANGELOG.md, README.md, src/adjusters/number.es, src/adjusters/string.es, src/libs/constants.es, src/libs/decorators/numberArray/each.es, src/libs/decorators/only.es, src/libs/decorators/stringArray/each.es, test/adjusters/number.test.es, test/adjusters/numberArray.test.es, test/adjusters/string.test.es, test/adjusters/stringArray.test.es, test/index.test.es
=> C: rename `.in()` to `.only()`

README.md
* update `adjuster.adjust()` examples
=> Update adjust examples

README.md
=> Feature update readme example

CHANGELOG.md, README.md, src/adjusters/number.es, src/libs/constants.es, src/libs/decorators/allowNull.es, test/adjusters/number.test.es
* `adjuster.number().allowNull()`
=> Feature add number allownull

CHANGELOG.md, README.md, src/adjusters/string.es, test/adjusters/string.test.es
* `adjuster.string().allowNull()`
=> A: `adjuster.string().allowNull()`

CHANGELOG.md, README.md, src/adjusters/numberArray.es, src/libs/constants.es, src/libs/decorators/numberArray/each.es, test/adjusters/numberArray.test.es
* `adjuster.numberArray().allowNull()`
* `adjuster.numberArray().eachAllowNull()`
=> A: `adjuster.numberArray().allowNull()`

CHANGELOG.md, README.md, src/adjusters/numericString.es, test/adjusters/numericString.test.es
* `adjuster.numericString().allowNull()`
=> A: `adjuster.numericString().allowNull()`

CHANGELOG.md, README.md, src/adjusters/email.es, src/adjusters/ipv4.es, src/adjusters/ipv6.es, test/adjusters/email.test.es, test/adjusters/ipv4.test.es, test/adjusters/ipv6.test.es
* `adjuster.ipv4().allowNull()`
* `adjuster.ipv6().allowNull()`
* `adjuster.email().allowNull()`
=> A: `adjuster.ipv4().allowNull()`

README.md
* move error handler to bottom in README
=> U: move error handler to bottom in README

npm-shrinkwrap.json, package.json
* use [`cross-env`](https://www.npmjs.com/package/cross-env) package for cross-platform
=> U: use `cross-env` package for cross-platform

package.json
* fix package version of [`cross-env`](https://www.npmjs.com/package/cross-env)
=> * fix package version of `cross-env`

README.md
* update description about loading
=> * update loading method in README

CHANGELOG.md, README.md, src/libs/AdjusterBase.es, src/libs/adjust.es
* description about error handler in `README.md`
* refactor default error handler
=> F: error handler in README

CHANGELOG.md, README.md, appveyor.yml, test/index.test.es
* support Microsoft Windows officially (test by [AppVeyor](https://www.appveyor.com/))
=> Feature appveyor

README.md, test/index.test.es
=> * update CI labels in README

CHANGELOG.md
=> * fix an error in `CHANGEOG.md`

README.md
* change CI badge target branch: develop -> master
=> change CI badge target branch

HOW_TO_RELEASE.md
=> add document about release

README.md
* add links for engine / license in README
=> add links for engine / license in README

.npmrc, HOW_TO_RELEASE.md
* Do not create `package-lock.json`.
=> Disable `package-lock.json`

CHANGELOG.md, src/libs/decorators/numericString/pattern.es
* follow `wrap-regex` option for ESLint
=> Feature eslint wrap regex

create-release-branch.sh
* add post processing to `create-release-branch.sh`
=> Add post processing to `create-release-branch.sh`

CHANGELOG.md, README.md, src/adjusters/email.es, src/adjusters/ipv4.es, src/adjusters/ipv6.es, src/adjusters/number.es, src/adjusters/numberArray.es, src/adjusters/numericString.es, src/adjusters/string.es, src/adjusters/stringArray.es, src/libs/decorators/acceptEmptyString.es, src/libs/decorators/acceptNull.es, src/libs/decorators/array/type.es, src/libs/decorators/numberArray/each.es, src/libs/decorators/stringArray/each.es, test/adjusters/email.test.es, test/adjusters/ipv4.test.es, test/adjusters/ipv6.test.es, test/adjusters/number.test.es, test/adjusters/numberArray.test.es, test/adjusters/numericString.test.es, test/adjusters/string.test.es, test/adjusters/stringArray.test.es
* rename method; `allowEmptyString()` to `acceptEmptyString()`
* rename method; `allowNull()` to `acceptNull()`
* rename method; `eachAllowEmptyString()` to `eachAcceptEmptyString()`
* rename method; `eachAllowNull()` to `eachAcceptNull()`
=> Rename method; `allowEmptyString()` to `acceptEmptyString()`

CHANGELOG.md, README.md, src/adjusters/number.es, src/libs/decorators/number/acceptSpecialFormats.es, test/adjusters/number.test.es
* `adjuster.number().acceptSpecialFormats()`
=> add `adjuster.number().acceptSpecialFormats()`

CHANGELOG.md, README.md, src/adjusters/number.es, src/adjusters/numberArray.es, src/libs/decorators/numberArray/each.es, test/adjusters/numberArray.test.es
* `adjuster.numberArray().eachAcceptSpecialFormats()`
=> add `adjuster.numberArray().eachAcceptSpecialFormats()`

README.md
=> some adjustment for README.md

create-release-branch
U: change color for command
F: fix typo
=> refactor release script

create-release-branch
C: update release URL for release script: https://github.com/shimataro/node-adjuster/releases -> https://github.com/shimataro/node-adjuster/releases/new
=> update release URL for release script

create-release-branch
* show URL to create pull-request in release script
=> URL for pull-request

README.md
* remove empty lines for example
=> update examples in README

create-release-branch
* update link format for semver
=> update semver error format

CHANGELOG.md, README.md, src/adjusters/numberArray.es, src/libs/decorators/numberArray/each.es, test/adjusters/numberArray.test.es
* add `adjuster.numberArray().eachInteger()`
=> ADD: `adjuster.numberArray().eachInteger()`

CHANGELOG.md, package.json
=> FIX: build error in Windows

CHANGELOG.md, README.md
* add introduction in `README.md`
=> ADD: Introduction in README.md

README.md
=> ADD: notice about installing

README.md
* change `NOTICE` to `NOTE` in README
=> CHANGE: NOTICE to NOTE in README

src/adjusters/numberArray.es, src/adjusters/numericString.es, src/adjusters/string.es, src/adjusters/stringArray.es, src/libs/decorators/array/maxLength.es, src/libs/decorators/array/minLength.es, src/libs/decorators/string/maxLength.es, src/libs/decorators/string/minLength.es, src/libs/decorators/stringArray/each.es
=> CHANGE: JSDoc type

README.md
* change introduction in README
=> CHANGE: introduction in README

README.md
=> ADD: example in README

package.json
=> OTHER: change test target directory; "dist" to "src"

package.json
* refactor `npm run build` and `npm run watch` method
=> OTHER: refactor build and watch methods

package.json
* prepend `./` for all directories
=> OTHER: prepend "./" for all directories

.babelrc
* remove unused babel plugin in `.babelrc`
=> OTHER: remove unused babel plugin in .babelrc

.babelrc, CHANGELOG.md, README.md, npm-shrinkwrap.json, package.json
* support ES Modules (`*.mjs`)
=> support ES Modules

.gitignore, .vscode/tasks.json
* add tasks setting file for [Visual Studio Code](https://code.visualstudio.com/)
=> vscode task

create-release-branch
* verify method is `npm run verify`!
=> FIX: verify method is in release script

CHANGELOG.md, README.md, src/adjusters/number.mjs, src/libs/decorators/number/type.mjs, src/libs/types.mjs, test/adjusters/number.test.mjs
* ADD: `adjuster.number().strict()`
=> ADD: `adjuster.number().strict()`

CHANGELOG.md, README.md, src/adjusters/string.mjs, src/libs/decorators/string/type.mjs, test/adjusters/string.test.mjs
* ADD: `adjuster.string().strict()`
=> ADD: `adjuster.string().strict()`

README.md
* add index of `adjuster.array()` in `README.md`
=> FIX: about array in README

CHANGELOG.md, README.md, src/adjusters/object.mjs, src/index.mjs, src/libs/decorators/object/constraints.mjs, src/libs/decorators/object/type.mjs, test/adjusters/object.test.mjs
=> ADD: adjuster.object()

src/libs/AdjusterError.mjs, src/libs/decorators/acceptEmptyString.mjs, src/libs/decorators/acceptNull.mjs, src/libs/decorators/array/each.mjs, src/libs/decorators/array/maxLength.mjs, src/libs/decorators/array/minLength.mjs, src/libs/decorators/array/type.mjs, src/libs/decorators/boolean/type.mjs, src/libs/decorators/default.mjs, src/libs/decorators/number/maxValue.mjs, src/libs/decorators/number/minValue.mjs, src/libs/decorators/number/type.mjs, src/libs/decorators/numericString/checksum.mjs, src/libs/decorators/numericString/pattern.mjs, src/libs/decorators/only.mjs, src/libs/decorators/string/maxLength.mjs, src/libs/decorators/string/minLength.mjs, src/libs/decorators/string/pattern.mjs, src/libs/decorators/string/type.mjs
* use `AdjusterError.raise()` for exception
=> REFACTOR: about AdjusterError

src/adjusters/array.mjs
* FIX: JSDoc for `adjuster.array()`
=> FIX: JSDoc for adjuster.array()

.eslintrc.yml
* enable some constraints
* use only single quote for string `'off'`
=> CHANGE: ESLint settings

README.md, src/libs/decorators/boolean/type.mjs, test/adjusters/boolean.test.mjs
* CHANGE: accept `"yes"` / `"on"` as `true`, `"no"` / `"off"` as `false` in `adjuster.boolean()`
=> CHANGE: accept strings in adjuster.boolean()

package.json
=> specify npm version

.eslintrc.yml, npm-shrinkwrap.json, package.json, test/adjusters/array.test.mjs, test/adjusters/boolean.test.mjs, test/adjusters/email.test.mjs, test/adjusters/ipv4.test.mjs, test/adjusters/ipv6.test.mjs, test/adjusters/number.test.mjs, test/adjusters/numericString.test.mjs, test/adjusters/object.test.mjs, test/adjusters/string.test.mjs, test/index.test.mjs
* import/extensions
* import/no-unresolved
=> add eslint rules for import

CHANGELOG.md, package.json
* `cross-env` must be in `dependencies`!
=> FiX: installation error!

npm-shrinkwrap.json, package.json
=> ADD: @types

README.md
* update introduction in `README.md`
=> CHANGE: update introduction in README

.babelrc, CHANGELOG.md, README.md, npm-shrinkwrap.json, package.json
* use `var adjuster = require("adjuster");` instead of `var adjuster = require("adjuster").default;`
=> CHANGE: export for CJS

README.md
* CHANGE: update `README.md` for loading
=> update README for loading

README.md, src/index.d.ts
* chainable methods return `this`
=> chainable method in ambient declaration

CHANGELOG.md, create-release-branch
* FIX: publish from brand new directory
=> FIX: publish method

README.md
* add import method for TypeScript
=> for TypeScript

CHANGELOG.md, README.md, create-release-branch, npm-shrinkwrap.json, package.json, src/index.d.ts
=> version 1.0.0-rc.1

.gitignore, .travis.yml, README.md, package.json
* use [Codecov](https://codecov.io/) for code coverage
=> code coverage

create-release-branch
* CHANGE: update commands for post-release in release script
=> CHANGE: release script

README.md
* FIX: domain check example in `README.md`
=> FIX: README

test/adjusters/array.test.mjs, test/adjusters/email.test.mjs, test/adjusters/ipv4.test.mjs, test/adjusters/ipv6.test.mjs, test/adjusters/number.test.mjs, test/adjusters/numericString.test.mjs, test/adjusters/object.test.mjs, test/adjusters/string.test.mjs
=> code coverage 100%!

.gitignore, .travis.yml, CHANGELOG.md, README.md, create-release-branch, npm-shrinkwrap.json, package.json, src/decorators/array/type.mjs, src/decorators/numericString/separatedBy.mjs, src/decorators/string/pattern.mjs, src/index.d.ts, test/adjusters/array.test.mjs, test/adjusters/email.test.mjs, test/adjusters/ipv4.test.mjs, test/adjusters/ipv6.test.mjs, test/adjusters/number.test.mjs, test/adjusters/numericString.test.mjs, test/adjusters/object.test.mjs, test/adjusters/string.test.mjs
* `adjuster.string().pattern()` and `adjuster.email().pattern()` accept only RegExp (reject string) #226
=> version 1.0.0-rc.2

README.md
* FIX: add missing double-quotation
* ADD: explanation of `AdjusterError`
=> proofreading

src/decorators/acceptEmptyString.mjs, src/decorators/acceptNull.mjs, src/decorators/array/each.mjs, src/decorators/array/maxLength.mjs, src/decorators/array/minLength.mjs, src/decorators/array/type.mjs, src/decorators/boolean/type.mjs, src/decorators/default.mjs, src/decorators/email/maxLength.mjs, src/decorators/number/maxValue.mjs, src/decorators/number/minValue.mjs, src/decorators/number/type.mjs, src/decorators/numericString/checksum.mjs, src/decorators/numericString/joinArray.mjs, src/decorators/numericString/pattern.mjs, src/decorators/numericString/separatedBy.mjs, src/decorators/object/constraints.mjs, src/decorators/object/type.mjs, src/decorators/only.mjs, src/decorators/string/maxLength.mjs, src/decorators/string/minLength.mjs, src/decorators/string/pattern.mjs, src/decorators/string/trim.mjs, src/decorators/string/type.mjs, src/index.d.ts, src/libs/AdjusterBase.mjs, src/libs/AdjusterError.mjs
* refactor decorator types in JSDoc
=> decorator in jsdoc

npm-shrinkwrap.json, package.json
* add `@types/core-js` / `@types/node`
=> defined types

npm-shrinkwrap.json, package.json
* update Babel to 7.0.0!
* move `babel-core` to `devDependencies`
=> package configuring

CHANGELOG.md, src/decorators/number/type.mjs, src/decorators/string/type.mjs, src/libs/types.mjs, test/adjusters/number.test.mjs
* CHANGE: `adjuster.number().adjust([])` causes `adjuster.CAUSE.TYPE`
=> CHANGE: number types

src/decorators/number/type.mjs
* use `!isNumber()` instead of `isNaN()`
=> refactor `adjuster.number()`

src/index.d.ts, src/libs/constants.mjs
* remove unused cause: `adjuster.CAUSE.ARRAY`
=> adjuster.CAUSE

CHANGELOG.md, src/index.d.ts
* CHANGE: collection types for TypeScript code
=> d.ts for typescript

src/libs/regexp/uri.mjs, test/adjusters/string.test.mjs
* add tests for HTTP pattern
* add comment for HTTP pattern
=> string pattern for HTTP

CHANGELOG.md, README.md, src/index.d.ts, src/index.mjs, test/index.test.mjs
* ADD: `adjuster.AdjusterError` for TypeScript
=> export `adjuster.AdjusterError`

CHANGELOG.md, README.md, npm-shrinkwrap.json, package.json, src/adjusters/email.mjs, src/index.d.ts, src/index.mjs, src/libs/constants.mjs, src/libs/regexp/email.mjs, src/libs/regexp/ipv4.mjs, src/libs/regexp/ipv6.mjs, src/libs/regexp/uri.mjs, test/adjusters/string.test.mjs, test/index.test.mjs
* `adjuster.AdjusterError` - for TypeScript #256 
* `adjuster.STRING.PATTERN.HTTP` - for test of HTTP/HTTPS URL #255 
* collection types for TypeScript code #253
=> version 1.0.0-rc.6

node-adjuster.code-workspace
* recommend Visual Studio Code plugin: [npm](https://marketplace.visualstudio.com/items?itemName=eg2.vscode-npm-script)
=> Visual Studio Code plugins

CHANGELOG.md, README.md, node-adjuster.code-workspace, npm-shrinkwrap.json, package.json, src/index.d.ts, src/index.mjs, test/index.test.mjs
* `adjuster.AdjusterError` - reverted v1.0.0-rc.6 #260
=> version 1.0.0-rc.7

.travis.yml, CHANGELOG.md, npm-shrinkwrap.json, package.json
=> version 1.0.0

CHANGELOG.md, npm-shrinkwrap.json, package.json
* fix [event-stream incident](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident)
=> fix event-strem incident

package.json, test/adjusters/array.test.mjs, test/adjusters/boolean.test.mjs, test/adjusters/email.test.mjs, test/adjusters/number.test.mjs, test/adjusters/numericString.test.mjs, test/adjusters/object.test.mjs, test/adjusters/string.test.mjs, test/index.test.mjs
* change module name in test; "index" -> "adjuster"
=> change module name in test

.travis.yml
=> automation NPM publishing

create-release-branch, package.json
* add package.json "--access=public"
=> set default access mode

.travis.yml
* accept `vX.Y.Z` branch on Travis CI
=> accept tags on Travis CI

test/adjusters/numericString.test.mjs
* add test of adjuster.numericString().default()
=> adjuster.numericString().default()

.travis.yml
* update `branches.only` on Travis CI
=> .travis.yml:branchs.only

.travis.yml, CHANGELOG.md, README.md, npm-shrinkwrap.json, package.json, src/index.d.ts
* `adjuster.array<T>()` returns type `T[]`
=> version 1.2.0

.eslintrc.yml
* add ["complexity" rule](https://eslint.org/docs/rules/complexity) in ESLint
=> ESLint rules

.eslintrc.yml, .travis.yml, appveyor.yml
* unindent arrays in YAML files
=> YAML style

CHANGELOG.md, src/index.d.ts
* export constraints type for TypeScript
=> add a type

create-release-branch
=> release branch name

CHANGELOG.md, npm-shrinkwrap.json, package.json
* update packages
* export constraints type for TypeScript
=> version 1.3.0

CHANGELOG.md, README.md, src/adjusters/number.mjs, src/decorators/map.mjs, src/index.d.ts, src/libs/constants.mjs, test/adjusters/number.test.mjs
=> adjuster.number().map()

.github/main.workflow, .travis.yml
use GitHub Actions
* <https://developer.github.com/actions/>
* <https://github.com/features/actions>
=> update publish method

src/example.ts
=> example.ts

CHANGELOG.md, npm-shrinkwrap.json, package.json
* `adjuster.number().map()`
* `adjuster.string().map()`
* `adjuster.numericString().map()`
=> version 1.3.1

.eslintrc.yml, CHANGELOG.md, README.md, src/adjusters/number.mjs, src/decorators/number/acceptFullWidth.mjs, src/index.d.ts, src/libs/string.mjs, test/adjusters/number.test.mjs
* `adjuster.number().acceptFullWidth()`
=> adjuster.number().acceptFullWidth()

CHANGELOG.md, README.md, src/adjusters/numericString.mjs, src/decorators/numericString/fullToHalf.mjs, src/decorators/numericString/fullWidthToHalf.mjs, src/index.d.ts, test/adjusters/numericString.test.mjs
* `adjuster.numericString().fullWidthToHalf()`
=> adjuster.numericstring().fullWidthToHalf()

CHANGELOG.md, npm-shrinkwrap.json, package.json
* `adjuster.number().acceptFullWidth()`
* `adjuster.numericString().fullWidthToHalf()`
* `adjuster.number().convert()`
* `adjuster.string().convert()`
* `adjuster.numericString().convert()`
* `adjuster.number().map()`
* `adjuster.string().map()`
* `adjuster.numericString().map()`
=> version 1.4.0

package.json
* do NOT update npm-check-updates
=> exclude npm-check-updates from updating

README.md, package.json
* update description of package
=> update description of package

.travis.yml, appveyor.yml
=> support Node.js v10

.travis.yml, appveyor.yml
=> support Node.js v12
